<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>CONTACTO</title>
	<link rel="stylesheet" type="text/css" href="icon/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap-grid.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap-rtl.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body style="background: url('img/LOGIN.png');background-size: 100%;">
	<h1 style="margin-left: 20px;"><img src="img/INTERELETRIC.png" width="13%"></h1>

	<?php
		include("stilo.html");
	?>

</body>
</html>